### PR TITLE
ngrep Enhancements

### PR DESCRIPTION
**Pull request by rwhalb**
Added new options for displaying the frame number for each matched packet, added option for disabling the default built in IP BPF filter, setting the exit code for a matched vs non-match session and displaying the total number of matched packets...

### CODE REVIEW

**Comment by jpr5** [comment]
Hi Ronald, 

Sorry for the late reply!  I appreciate you taking the time to develop and submit these patches.  I'm curious about the motivation behind some of them, before I merge anything in.

What was your use case for `-f`?  Just trying to understand what challenge you ran into that numbering/totaling the matched frames solved.  Same for `-z` -- was there a problem you encountered that disabling the default filter solved?  

As for the exit status patch, I don't think I can accept that one.  Non-zero exit codes are almost universally for communicating error conditions, and many automation tools would misinterpret a non-zero exit (I can't think of a use case for ngrep specifically, but in principle this is true).

cheers,
--jordan

**Comment by rwhalb** [comment]
Jordan:

Thank you for your reply. Motivations for each suggested enhancement:

-f => Displays the frame number prepended to the matching packet output and also includes the match count. In the example below this allows one to further investigate packets 42 and 46 (I.e., matching packets that contain the ascii string: "CAPABILITY". 

Example:
[root@nst26-vm tmp]# ngrep -T -f -z -I "/var/nst/wuiout/wireshark/capture_netmon0.cap" 'CAPABILITY';
input: /var/nst/wuiout/wireshark/capture_netmon0.cap
match: CAPABILITY
##########################################
42: T +4294787352.256432 108.44.41.213:51716 -> 152.163.0.65:143 [AP]
  h2y8 CAPABILITY..                                                                                                              
####
46: T +0.012226 152.163.0.65:143 -> 108.44.41.213:51716 [AP]
  * CAPABILITY IMAP4rev1 UIDPLUS ID NAMESPACE LOGIN-REFERRALS IDLE STARTTLS AUTH=XAOL-UAS-MB AUTH=XOAUTH2 STARTTLS..h2y8 OK completed..                                                                                                                         
######################################################exit
matches: 2

-z => Disable using the built in BPF IP Filter and do not show in the output. In the example below - same as above but the BPF IP filter is used and shown below.

Example:
[root@nst26-vm tmp]# ngrep -T -f -I "/var/nst/wuiout/wireshark/capture_netmon0.cap" 'CAPABILITY';
input: /var/nst/wuiout/wireshark/capture_netmon0.cap
filter: ((ip || ip6) || (vlan && (ip || ip6)))
match: CAPABILITY
##########################################
42: T +4294787085.966999 108.44.41.213:51716 -> 152.163.0.65:143 [AP]
  h2y8 CAPABILITY..                                                                                                              
####
46: T +0.012226 152.163.0.65:143 -> 108.44.41.213:51716 [AP]
  * CAPABILITY IMAP4rev1 UIDPLUS ID NAMESPACE LOGIN-REFERRALS IDLE STARTTLS AUTH=XAOL-UAS-MB AUTH=XOAUTH2 STARTTLS..h2y8 OK completed..                                                                                                                         
######################################################exit
matches: 2

Lastly: A zero exit status means one or more matches were found otherwise a non-zero exit status is returned. This behavior is similar to the grep command.

---Ron Henderson
Co-Author or the Network Security Toolkit (NST)

**Comment by jpr5** [comment]
OK, so let me see if I have this straight:

(1) Show the frame number and (2) show the number of matches upon exit - got it.  I may differ on the how, but I can get on board with that.
(3) Make exit codes work like grep's -- OK I think I can get on board with that too.  I just checked BSD vs. GNU grep and they match on this, so that's good.

(4) Disable the IP filter restriction - I'm still not sure from what you pasted, but I think the gist is "hey don't limit me to IP packets"?  If so, then my response is that ngrep's entire functionality rests on the assumption that it's looking at IP traffic, header offset calculations and all, which is why the enforcement is there.  I don't even know what it'd do with non-IP traffic, but I have to assume it's not that useful?  Help me understand, if I'm confused on this one.

**Comment by rwhalb** [comment]
Jordan:

Thank you for the acceptance of 1,2 and 3. The '-z' option was a way for me to avoid any packet filtering at all (I.e., don't even apply a default one). Not necessary now based on your discussion above. Thank you for your support and contribution. I will be including ngrep into the pending release of NST 26. I have a nice web interface front end to ngrep in the NST WUI single and multi-tap network packet capture interface pages...

---Ron Henderson
Co-Author of NST

**Comment by jpr5** [comment]
Wonderful, thanks again for the feedback.  

Gonna close this pull request, as the functionality is now in master.  

Hold tight for a 1.47 release shortly.

**Pull request closed without merging**
